version: '3.7'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
      SPARK_EVENTLOG_ENABLED: "true"
      SPARK_EVENTLOG_DIR: /tmp/spark-events
      USER: root
      LOGNAME: root
      HOME: /root
    volumes:
      - spark-events:/tmp/spark-events
      - ./spark-apps:/opt/spark-apps

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - "spark-master"
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_EVENTLOG_ENABLED: "true"
      SPARK_EVENTLOG_DIR: /tmp/spark-events
    volumes:
      - spark-events:/tmp/spark-events
      - ./spark-apps:/opt/spark-apps

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - "spark-master"
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_EVENTLOG_ENABLED: "true"
      SPARK_EVENTLOG_DIR: /tmp/spark-events
    volumes:
      - spark-events:/tmp/spark-events
      - ./spark-apps:/opt/spark-apps

  spark-history-server:
    image: bitnami/spark:latest
    container_name: spark-history-server
    command: bin/spark-class org.apache.spark.deploy.history.HistoryServer
    ports:
      - "18080:18080"
    environment:
      SPARK_HISTORY_OPTS: >
        -Dspark.history.fs.logDirectory=/tmp/spark-events
        -Dspark.history.ui.port=18080
    volumes:
      - spark-events:/tmp/spark-events
      - ./spark-apps:/opt/spark-apps

volumes:
  spark-events:
